### ISSUE TITLE
Adapt the library to the latest Hibernate Validator version

### ISSUE THREAD

**Issue by Obirah** [rcapraro/kalidation#11]
With Hibernate validator 6.1.x the constructor of `DefaultConstraintMapping` changed from `public DefaultConstraintMapping()` to `public DefaultConstraintMapping(JavaBeanHelper javaBeanHelper)`.

Because of this change, I ran into a NoSuchMethodException (`method 'void <init>()' not found`) when using Kalidation in a Spring Boot project that already transitively contained a Hibernate validator 6.1.x dependency. Explicitly adding 6.0.x solved the problem.

I don't think this is a very pressing issue since there's a workaround, but I wanted to place this piece of information here, so that others can find it, if they stumble across the problem as well.

**Comment by rohte** [comment]
I ran into this as well. Thanks for the comment.

**Comment by rcapraro** [comment]
Thank you for reporting this issue !
Please note that Kalidation version 1.5 now supports Hibernate validator 6.1.5

**Comment by rcapraro** [comment]
Fixed in Kalidation 1.5
