### ISSUE TITLE
validate function returns Boolean as value

### ISSUE THREAD

**Issue by clojj** [rcapraro/kalidation#14]
Looking at the implementation of
`fun validate(constrainedClass: Any): Validated<Set<ValidationResult>, Boolean>`

What is the reasoning for Boolean, instead of returning the validated value (constrainedClass Any) here ?
Especially, when using validate() in a monad-comprehension from Arrow (since it returns the Arrow type!), one could use the monadic computation in a straightforward way. Having to continue with `if (valid)` feels not natural in a monad-comprehension.

**Comment by rcapraro** [comment]
Hi,
thanks for this excellent suggestion, il will provide a new version (1.6.2) with it.

Kind regards
