### ISSUE TITLE
FEATURE : should have a new constraint 'exactSize'

### ISSUE THREAD

**Issue by PierreLeresteux** [rcapraro/kalidation#18]
We have the `size` function for a CharSequence, but for a fixed length the code is not optimized and the error message neither.

```
constraints<MyObject> {
      property(MyObject::textField) {
          notEmpty()
          size(14,14)
      }
  }
```

And in case of error : `{"field":"textField","message":"size must be between 14 and 14"}`

It should be something like that : 

```
constraints<MyObject> {
      property(MyObject::textField) {
          notEmpty()
          size(14)
      }
  }
```

or 

```
constraints<MyObject> {
      property(MyObject::textField) {
          notEmpty()
          exactSize(14)
      }
  }
```

with the message : `{"field":"textField","message":"size must be 14"}`

Thanks, Grazie

**Comment by rcapraro** [comment]
grazie mille !

Added in release v1.9.0
