### ISSUE TITLE
ConstraintRule is sealed, why?

### ISSUE THREAD

**Issue by geertmulders** [rcapraro/kalidation#22]
Currently I'm trying to implement my own extension on `fun Constraint<out Any, out CharSequence?>`: 

```
fun Constraint<out Any, out CharSequence?>.passwordStrength(min: Int = 4, message: String? = null) {
    constraintRules.add(PasswordStrengthRule(min))
}
```

The problem is however that there is no way to implement `PasswordStrengthRule`, since I cannot extend `ConstraintRule` because it is sealed. 

In the code I cannot find any good reason for `ConstraintRule` to be sealed. Is it possible to get it "unsealed"?

This would also allow the library to be split up into multiple modules; e.g. one core module with the actual logic and most of the validations and another module with the `validByScript`; a nice feature, but very weighty on the dependencies.

**Comment by amr** [comment]
Hey @geertmulders, I see you closed this, but I came here to ask the same question. Mind sharing how you went about implementing your custom rule?

**Comment by geertmulders** [comment]
Hi @amr I didn't; I switched to Konform, but since that missed some serious features as well, I ended up forking Konform, which resulted in [konfork](http://github.com/konfork/konfork) (note: changes are still te be expected)
