### ISSUE TITLE
How to extend validators

### ISSUE THREAD

**Issue by ornolisvt** [rcapraro/kalidation#4]
I think that is a great library, but I would like to know how to implement a custom validator, for example, compare two fields for equality (password and repeat password)

**Comment by rcapraro** [comment]
Hi,
thank you for your interest in Kalidation.
Cross field validation is on the backlog for a future version of Kalidation.

In the meantime, you can use a function to validate the two password fields:

In your class:
`fun validatePasswords(): Boolean = this.password == this.repeatPassword`

And then in Kalidation
```
constraints<ClassWithMethods> {
    property(ClassWithMethods::xxxx) {
      ///
  }
    returnOf(ClassWithMethods::validatePasswords) {
        assertTrue()
  }
```

Hope this helps,.
Regards,
Richard

**Comment by rcapraro** [comment]
Closed
